### ISSUE TITLE
API stop working again: Exception "quoteResponse" \ 404 (Not Found)

### ISSUE THREAD

**Issue by E-Moses** [dshe/YahooQuotesApi#16]
** Updated post **

Continue to Issues 12, 13.
https://github.com/dshe/YahooQuotesApi/issues/12
https://github.com/dshe/YahooQuotesApi/issues/13

When running Yahoo V6:
https://query2.finance.yahoo.com/v6/finance/quote?formatted=true&lang=en-US&symbols=AAPL
Getting the result:
{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}

** looks like V6 is no longer available!  that can explain why the latest component version stop working **

---
When running Yahoo V7:
https://query2.finance.yahoo.com/v7/finance/quote?formatted=true&lang=en-US&symbols=AAPL
Getting the result (as last week):
{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}

---
Using the latest version of the package (from last week) -
When running from C# getting the exception:

System.IO.InvalidDataException: quoteResponse
   at YahooQuotesApi.YahooSnapshot.MakeRequest(Uri uri, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 111
   at YahooQuotesApi.YahooSnapshot.<GetElements>b__7_1(ValueTuple`2 data, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 66
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at YahooQuotesApi.YahooSnapshot.GetElements(Symbol[] symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 65
   at YahooQuotesApi.YahooSnapshot.Producer(Symbol[] symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 38
   at YahooQuotesApi.SerialProducerCache`2.Get(HashSet`1 keys, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Utilities\SerialProducerCache.cs:line 37
   at YahooQuotesApi.YahooSnapshot.GetAsync(HashSet`1 symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 31
   at YahooQuotesApi.Quotes.GetSecuritiesAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 49
   at YahooQuotesApi.Quotes.GetAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 35
   at YahooQuotesApi.YahooQuotes.GetAsync(IEnumerable`1 symbols, Histories historyFlags, String historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\YahooQuotes.cs

---

Can you please check/fix it?

Thanks!

**Comment by E-Moses** [comment]
Is it working for anyone?

**Comment by rwb196884** [comment]
Yep, bust again.

**Comment by kyi87** [comment]
Yes, same problem here -.-

**Comment by jbadilloprotipo0** [comment]
yeah, same problem

**Comment by leacasas** [comment]
Found a way to generate the crumb value, taken from this post:

https://stackoverflow.com/questions/76065035/yahoo-finance-v7-api-now-requiring-cookies-python

1. Make HTTP GET call to URL [https://fc.yahoo.com/](https://fc.yahoo.com/). Although this call result in a **404** error, we just need it to extract **set-cookie** from response headers which is then used in the subsequent calls.
2. Now make an HTTP GET call to the URL [https://query2.finance.yahoo.com/v1/test/getcrumb](https://query2.finance.yahoo.com/v1/test/getcrumb), by including the obtained cookie from the previous response headers. This call will retrieve the crumb value.
3. Replace [crumb-value] in the following URL and make a HTTP GET call with cookie [https://query2.finance.yahoo.com/v7/finance/quote?symbols=TSLA&crumb=[crumb-value]](https://query2.finance.yahoo.com/v7/finance/quote?symbols=TSLA&crumb=%5Bcrumb-value%5D)
4. Cache the cookie value and crumb value to skip first two steps going forward

**Comment by E-Moses** [comment]
@leacasas 
Nice Idea.
Crossing our fingers for you... :)

**Comment by nsulikowski** [comment]
This problem resurfaced for me yesterday:

```
YahooQuotes yahooQuotes = new YahooQuotesBuilder(apiVersion: "v6")
    .WithHistoryStartDate(start: Instant.FromUtc(year: args.Start.Year, monthOfYear: args.Start.Month, dayOfMonth: args.Start.Day, hourOfDay: 0, minuteOfHour: 0))
    .Build();
```

Error:
```
RootElement = ValueKind = Object : "{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}"
```

**Comment by leacasas** [comment]
Added PR #17

**Comment by nsulikowski** [comment]
Awesome. Thanks @leacasas , from another fellow Argentinean.

**Comment by E-Moses** [comment]
@leacasas is the problem solved?

If so, did you also create a Nugat repository for it? Can I find it In Visual Studio?

thanks!

**Comment by sachatomey** [comment]
I've just upgraded the component from NuGet in VS and it worked a treat.

Thanks all !

Hopefully we'll have some stability for a while now :/

**Comment by E-Moses** [comment]
@leacasas or @dshe - can you handle the issue PLEASE...
