### ISSUE TITLE
"No cookies found." Exception

### ISSUE THREAD

**Issue by Monthon-Paul** [dshe/YahooQuotesApi#27]
Hello, liked your project but what can cause this situation with "No cookies found" exception. My application have some GUI aspect and it's a small project. I have never ran into this issue with just a class library or console application. Is it not compatible with .NET MAUI?

No cookies found.
   at YahooQuotesApi.CookieAndCrumb.GetCookieAndCrumb1(CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\CookieAndCrumb.cs:line 53
   at YahooQuotesApi.CookieAndCrumb.Get(CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\CookieAndCrumb.cs:line 31
   at YahooQuotesApi.YahooSnapshot.GetElements(List`1 symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 61
   at YahooQuotesApi.YahooSnapshot.Producer(List`1 symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 43
   at YahooQuotesApi.SerialProducerCache`2.<Get>d__5[[YahooQuotesApi.Symbol, YahooQuotesApi, Version=5.5.5.202, Culture=neutral, PublicKeyToken=null],[YahooQuotesApi.Security, YahooQuotesApi, Version=5.5.5.202, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Utilities\SerialProducerCache.cs:line 37
   at YahooQuotesApi.YahooSnapshot.GetAsync(HashSet`1 symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 33
   at YahooQuotesApi.Quotes.GetSecuritiesAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 49
   at YahooQuotesApi.Quotes.GetAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 40
   at YahooQuotesApi.YahooQuotes.GetAsync(IEnumerable`1 symbols, Histories historyFlags, String historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\YahooQuotes.cs:line 38
   at YahooQuotesApi.YahooQuotes.GetAsync(String symbol, Histories historyFlags, String historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\YahooQuotes.cs:line 20

**Comment by dshe** [comment]
Please try with the new version 5.5.6 and let us know if there are any problems remaining.

**Comment by Monthon-Paul** [comment]
Still having the same issue of "No cookies found" does it have anything to do with await/async in MAUI, I have the same code example from the README

**Comment by dshe** [comment]
- Try disabling HttpResilience as follows:
```
    YahooQuotes yahooQuotes = new YahooQuotesBuilder()
            .WithoutHttpResilience()
            .Build();
```
- Try opening the YahooQuotesApi solution on your machine and running the tests.
- Try running the tests using a VPN (such as the free Proton VPN), with a connection to USA, then Europe.

I am not aware of any specific incompatibility between YahooQuotesApi and MAUI. However, MAUI itself does seem to have some async initialization issues.

**Comment by Monthon-Paul** [comment]
I ran the solution with the provided tests and I even created MSUnit test of my own for testing with a Class Library, it all works, which is great! But when using .Net MAUI I always get this exception thrown
I also tried `YahooQuotes yahooQuotes = new YahooQuotesBuilder().WithoutHttpResilience().Build();` but it didn't help with it.

**Comment by leacasas** [comment]
@Monthon-Paul  is there a way that you can share the code snippet where you're using this library? is there anything in particular with the way you're using it?

You receive that because the http clients need to add some cookies to the http header in order to request for quotes from Yahoo Finance API. There's a process involved in getting those cookies, and that's where you're stumbling upon this issue, the code isn't finding the usable cookies.

**Comment by Monthon-Paul** [comment]
Yeah sure I have a method in one of my MAUI .cs file that looks like this, (there are extra detail but this is the main code):
````
using Library;
...
private async void SelectStock(object sender, SelectedItemChangedEventArgs e) {
           // This works
            if (e.SelectedItem != null) {
			Symbol = e.SelectedItem; 

			try {
				// This doesn't work
				stock = await Library.GetStockData(Symbol);
                                 ... // irreverent
                        catch (Exception ex) {
                                 Console.WriteLine(ex.Message); // print "No cookies found"
                        }
               }
}
````

It would go to a Class Library where it would simply just go to this method:

````
public static async Task<StockData> GetStockData(string symbol) {
		var yahooQuotes = new YahooQuotesBuilder().WithoutHttpResilience().Build();
		var security = await yahooQuotes.GetAsync(symbol) ?? throw new Exception($"Failed to retrieve data ");
                 ... // irreverent
}
````

it would do a long pause for the GetStockData method when debugging but when I continue it would go straight to the exception to print out the message. This is all happening from me using Microsoft MAUI with a Class Library.

**Comment by dshe** [comment]
`YahooQuotes` should be built once and then used throughout your application. You should not build a new `YahooQuotes` for each request.

```
// do this once in your application
YahooQuotes yahooQuotes = new YahooQuotesBuilder().Build();

// use YahooQuotes to make some requests
var result1 = yahooQuotes.Get...(...); 
var result2 = yahooQuotes.Get...(...); 
```

**Comment by Monthon-Paul** [comment]
So I have moved yahooQuotes to now be declare once, I even tested it now in my single MAUI file and I am still getting the same exception thrown. Any more ideas would be nice 
````
private YahooQuotes yahooQuotes;

public MainPage() {
     yahooQuotes = new YahooQuotesBuilder().WithoutHttpResilience().Build();
     ...
}

private async void SelectStock(object sender, SelectedItemChangedEventArgs e) {
           // This works
            if (e.SelectedItem != null) {
			Symbol = e.SelectedItem; 

			try {
				// This doesn't work
				var security = await yahooQuotes.GetAsync(Symbol)
                                 ... // irreverent
                        catch (Exception ex) { // <-- goes to here
                                 Console.WriteLine(ex.Message); // print "No cookies found"
                        }
               }
}
````

**Comment by dshe** [comment]
@Monthon-Paul 

I cloned your **StockMarketSim** solution. But I could not duplicate the issue. When I run the program in my environment, the following line does not fail:

`stock = await Portfolio.GetStockData(FrontSTK.Symbol);`

I suggest that you add the **YahooQuotesApi** project to your solution, which will enable you to debug the issue directly.

**Comment by Monthon-Paul** [comment]
Oh, by last chance if you have forked it, I have replaced with `var security = await yahooQuotes.GetAsync(FrontSTK.Symbol)` within the method, if this line succeed and doesn't go into the exception, then it is problem with my system perhaps.

**Comment by dshe** [comment]
@Monthon-Paul 

I updated your **StockMarketSim** solution. I still could not duplicate the issue.

Incidentally, I noticed `MethodAsync.Result` is being called on some async methods:

https://tooslowexception.com/the-danger-of-asyncawait-and-result-in-one-picture/
