### ISSUE TITLE
System.Text.Json.JsonReaderException: 'T' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

### ISSUE THREAD

**Issue by twestosaurus** [dshe/YahooQuotesApi#28]
Hi, first of al again thank you for this great library! After the EU cookies issue it worked great for the last few months but since yesterday I'm getting the following exception:

```
System.Text.Json.JsonReaderException: 'T' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at YahooQuotesApi.YahooSnapshot.MakeRequest(Uri uri, List`1 cookie, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 102
   at YahooQuotesApi.YahooSnapshot.<>c__DisplayClass18_0.<<GetElements>b__1>d.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 75
```

This is the calling line:

`Security security = await MyYahooQuotes.GetAsync(index, Histories.All) ?? throw new ArgumentException("Unknown symbol." + index);`

...where index is the ticker I'm looking for. Does anyone have an idea what might be the cause for this? I'm completely clueless.

**Comment by E-Moses** [comment]
Yep, it is happening to me too.
start about ~14 hours ago.

**Comment by twestosaurus** [comment]
@E-Moses yep, I upgraded to the latest version, no success

**Comment by dshe** [comment]
Thank you for your report. Please try the new version 5.5.7.

**Comment by twestosaurus** [comment]
@dshe thanks for the incredibly quick respsonse and update! - however now I'm back to the "no cookies found" error

```
System.InvalidOperationException: No cookies found.
   at YahooQuotesApi.CookieAndCrumb.GetCookieAndCrumb1(CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\CookieAndCrumb.cs:line 41
```

**Comment by zeabee** [comment]
5.5.7 now works through VPN in US (which 5.5.6 did not). Same issue as @twestosaurus in Europe. Not sure if this helps debugging.

**Comment by E-Moses** [comment]
My application uses an older version of the lib - taken after the last big problem, couple of month ago.
It stopped working yesterday with the error that @twestosaurus described.

Surprisingly - it returns to work ~30 minutes ago...
I have changed nothing - Its just return to work...

FYI @dshe

**Comment by twestosaurus** [comment]
Indeed, seems to work again - so I guess this can be closed.

**Comment by zeabee** [comment]
5.5.6 works now but with 5.5.7 I get "No cookies found" in Europe. 5.5.7 works through US VPN.

**Comment by twestosaurus** [comment]
@zeabee you're right - I've two projects, one using 5.5.6. and the other one using 5.5.7, only 5.5.6 seems to work from EU
