### ISSUE TITLE
System.InvalidOperationException: 'No cookies found.' at YahooQuotesApi.CookieAndCrumb

### ISSUE THREAD

**Issue by rwb196884** [dshe/YahooQuotesApi#29]
Version 5.5.7.

Thrown when calling`yahooQuotes.GetAsync`
```
            foreach (Equity equity in _Db.Equities.ToList(/* materialise */))
            {
                    DateTime d = _Db.Prices.Where(z => z.Symbol == equity.Symbol).Select(z => z.Date).ToList().DefaultIfEmpty(DateTime.UtcNow.AddDays(-14)).Max();
                    YahooQuotes yahooQuotes = new YahooQuotesBuilder().WithHistoryStartDate(Instant.FromDateTimeUtc(d.ToUniversalTime())).Build();
                    _Logger.LogInformation($"  Getting prices from {d:yyyy-MM-dd}.");
                    Security s = await yahooQuotes.GetAsync(equity.Symbol, Histories.PriceHistory);
```

Stak trace: 
```
   at YahooQuotesApi.CookieAndCrumb.<GetCookieAndCrumb1>d__6.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Core\CookieAndCrumb.cs:line 37
   at YahooQuotesApi.CookieAndCrumb.<Get>d__5.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Core\CookieAndCrumb.cs:line 28
   at YahooQuotesApi.YahooSnapshot.<GetElements>d__18.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 61
   at YahooQuotesApi.YahooSnapshot.<Producer>d__17.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 43
   at YahooQuotesApi.SerialProducerCache`2.<Get>d__5.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Utilities\SerialProducerCache.cs:line 47
   at YahooQuotesApi.YahooSnapshot.<GetAsync>d__16.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 33
   at YahooQuotesApi.Quotes.<GetSecuritiesAsync>d__14.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 49
   at YahooQuotesApi.Quotes.<GetAsync>d__13.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 35
   at YahooQuotesApi.YahooQuotes.<GetAsync>d__6.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\YahooQuotes.cs:line 38
   at YahooQuotesApi.YahooQuotes.<GetAsync>d__4.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\YahooQuotes.cs:line 20
   at Rwb.Equities.App.ProgramAsync.<UpdatePricesAsync>d__7.MoveNext() in C:\Work\github\equities\Rwb.Equities.App\ProgramAsync.cs:line 77
```

**Comment by MickDKhorne** [comment]
Same problem here (from Europe, as it may be the origin (US vs EU)).

using .WithoutHttpResilience() or the UserAgent doesn't correct the problem.

**Comment by rwb196884** [comment]
Working; thank you.

**Comment by MickDKhorne** [comment]
it's working for me too !
Thank you
