### ISSUE TITLE
API stop working - Exception: 'T' is an invalid start of a value

### ISSUE THREAD

**Issue by E-Moses** [dshe/YahooQuotesApi#31]
Start getting the following exception in the last hours:
Does anyone else getting it?

Looks similar to #28 

Exception:
System.Text.Json.JsonReaderException: 'T' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at YahooQuotesApi.YahooSnapshot.MakeRequest(Uri uri, IEnumerable`1 cookieValue, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 127
   at YahooQuotesApi.YahooSnapshot.<>c__DisplayClass8_0.<<GetElements>b__1>d.MoveNext() in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 77
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at YahooQuotesApi.YahooSnapshot.GetElements(Symbol[] symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 76
   at YahooQuotesApi.YahooSnapshot.Producer(Symbol[] symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 45
   at YahooQuotesApi.SerialProducerCache`2.Get(HashSet`1 keys, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Utilities\SerialProducerCache.cs:line 37
   at YahooQuotesApi.YahooSnapshot.GetAsync(HashSet`1 symbols, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Snapshot\YahooSnapshot.cs:line 35
   at YahooQuotesApi.Quotes.GetSecuritiesAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 49
   at YahooQuotesApi.Quotes.GetAsync(HashSet`1 symbols, Histories historyFlags, Symbol historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\Core\Quotes.cs:line 35
   at YahooQuotesApi.YahooQuotes.GetAsync(IEnumerable`1 symbols, Histories historyFlags, String historyBase, CancellationToken ct) in C:\projects\yahooquotesapi\YahooQuotesApi\YahooQuotes.cs:line 38
   at StocksAlerter.StocksDAL.GetStocksFromYahooAsync(IEnumerable`1 stocksSymbol, Nullable`1 stockDailyTradeSummaryStartUDateTime)

**Comment by E-Moses** [comment]
Gone after upgraded to latest version.
